### ISSUE TITLE
Missing Climdex Indices

### ISSUE THREAD

**Issue by Pouriya-J** [ECCC-CCCS/CMIP6-BCCAQ-Quality-Control#27]
@ssobie  I have noticed that the following files are missing in Climdex: 
**CanESM5_ssp585_r1i1p2f1 (missing 2 .nc files)**

- r99daysETCCDI_ann_BCCAQ2v2+ANUSPLIN300_CanESM5_historical+ssp585_r1i1p2f1_1950-2100.nc
- r99pETCCDI_ann_BCCAQ2v2+ANUSPLIN300_CanESM5_historical+ssp585_r1i1p2f1_1950-2100.nc

**EC-Earth3-Veg_ssp126_r1i1p1f1 (missing 13 .nc files)**

- suETCCDI_ann_',
- 'tn10pETCCDI_mon_',
- 'tn90pETCCDI_mon_',
- 'tnnETCCDI_mon_',
- 'tnxETCCDI_mon_',
- 'trETCCDI_ann_',
- 'tx10pETCCDI_mon_',
- 'tx90pETCCDI_mon_',
- 'txnETCCDI_mon_',
- 'txxETCCDI_mon_',
- 'wsdiETCCDI_ann_'

**Comment by ssobie** [comment]
This appears to be a transfer issue. The files exist and are complete on the PCIC system. I've sent new links to Dae Il and he should have the files shortly.

**Comment by cpomer10** [comment]
All good now - thanks @ssobie
