### ISSUE TITLE
Missing p99 variables at CRIM and Ouranos

### ISSUE THREAD

**Issue by juliettelavoie** [ECCC-CCCS/CMIP6-BCCAQ-Quality-Control#29]
The data that was transfered from PCIC to CRIM and Ouranos is missing 3 files of derived climdex indicators.
The missing files are for the indicators `r99p`, `r99store` and `r99days` for CanESM5_ssp585_r1i1p2f1.
CRIM will need the data to be able to calculate the 30 year mean and the ensemble stats.

An email has already been sent to PCIC to ask for the data.

**Comment by ssobie** [comment]
R99p and R99days were obtained from ECCC and I sent the R99store file to Juliette directly.
